Farm Table
CREATE TABLE Farm (
    FarmID   VARCHAR(50) NOT NULL PRIMARY KEY,
    FarmName VARCHAR(50) NOT NULL,
    UserID   VARCHAR(50) NOT NULL,
    CONSTRAINT fk_farm_user
        FOREIGN KEY (UserID)
        REFERENCES User(UserID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
